### ISSUE TITLE
(Possible) integer overflow in closepairs() when number of points in pattern equals 1

### ISSUE THREAD

**Issue by MartenMM** [spatstat/spatstat.geom#8]
When running `closepairs()` on a subset of unknown size I encountered 'Error: cannot allocate vector of size 16.0 Gb'. Apparently, the subset had size 1. I suspect an unsigned integer overflow in the underlying C implementation (e.g. when there is a `N - 2` somewhere with `N == 1` so that -1 = 2^32 = 4 billion 32-bits floating point numbers = 16 Gb). 

A reproducible example:
```
library("tidyverse")
library("sf")
library("spatstat")

sf <- tibble(x=0, y=0) %>% 
  st_as_sf(coords = c("x", "y"))
ppp <- as.ppp(sf)

closepairs(ppp, rmax = 1, distinct = FALSE)

# Error: cannot allocate vector of size 16.0 Gb
# In addition: Warning message:
#   Estimated number of close pairs exceeds maximum possible integer 
```

This bug also applies to `crosspairs()` under similar circumstances. The same error occurs when `distinct = TRUE` is set. In the case described in the example I would expect a single pair to be returned, in the latter case I would expect a null result.

Edit (relevant information from `sessionInfo()`):

- R version: 4.1.2 (2021-11-01)
- Platform: x86_64-w64-mingw32/x64 (64-bit)
- spatstat version: spatstat_2.3-0

**Comment by rubak** [comment]
Thanks for bringing this to our attention. This is really because the
converted point pattern from `sf` is unfortunate. In `spatstat` we expect a
point pattern to be a region of space with strictly positive area together
with observed points in that region. The conversion from `sf` uses the
bounding box as the region which is a single point of zero area in this case.
Below is a simpler reproducible example, but on my machine this only gives a
warning. Does it generate an error on your machine? Basically an overshot
of the possible number of close points is calculated which involves dividing
by the area of the region, which is `Inf` in this case, and it seems the way
that this is handled later on may be machine specific.

``` r
library(spatstat.geom)
W <- owin(c(0,0), c(0,0))
X <- ppp(0, 0, window = W)
closepairs(X, 1, distinct = FALSE)
#> Warning: Estimated number of close pairs exceeds maximum possible integer
#> $i
#> [1] 1
#> 
#> $j
#> [1] 1
#> 
#> $xi
#> [1] 0
#> 
#> $yi
#> [1] 0 0
#> 
#> $xj
#> [1] 0
#> 
#> $yj
#> numeric(0)
#> 
#> $dx
#> [1] 0
#> 
#> $dy
#> [1] 0
#> 
#> $d
#> [1] 0
```

When the window of observation has positive area everything works as expected
without the warning:

``` r
Window(X) <- owin(c(-.1,.1), c(-.1,.1))
closepairs(X, 1, distinct = FALSE)
#> $i
#> [1] 1
#> 
#> $j
#> [1] 1
#> 
#> $xi
#> [1] 0
#> 
#> $yi
#> [1] 0 0
#> 
#> $xj
#> [1] 0
#> 
#> $yj
#> numeric(0)
#> 
#> $dx
#> [1] 0
#> 
#> $dy
#> [1] 0
#> 
#> $d
#> [1] 0
```

I expect that we will implement something to check for an empty window in the
next release. Until then you will have to modify the observation window
manually as shown above. Does that fix the problem for you?

**Comment by rubak** [comment]
@baddstats I'm worried about the returned values of `yi` and `yj`, so maybe we should have a closer look soon(ish). I don't think we use these values very often (if ever) since we are usually just interested in indices and distances, which are correct.

**Comment by baddstats** [comment]
@rubak Good that you spotted the problem with `yi` and `yj` !

It seems to occur at line 453 of `closepairs.R`. It looks like a cut-and-paste error.
This line is invoked when `distinct=FALSE` and `what="all"`.

We use the coordinates `xi, xj, yi, yj` in the translation correction for summary functions -- but only for `distinct=TRUE`, so hopefully this bug does not affect them.

There are many lines of test code that verify correctness of closepairs() but this case was not included!

**Comment by baddstats** [comment]
This is now fixed in the development version `spatstat.geom 2.3-2.001`

**Comment by MartenMM** [comment]
Thanks @rubak and @baddstats for the quick response and solution. I have run the simpler reprex and still encountered an error in the latest CRAN version. The problem was solved after installing `spatstat.geom 2.3-2.001`. 

```
library(spatstat.geom)
W <- owin(c(0,0), c(0,0))
X <- ppp(0, 0, window = W)
closepairs(X, 1, distinct = FALSE)
# Error: cannot allocate vector of size 16.0 Gb
# In addition: Warning message:
#   Estimated number of close pairs exceeds maximum possible integer 

sessionInfo()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-w64-mingw32/x64 (64-bit)
# Running under: Windows 10 x64 (build 22000)
# 
# Matrix products: default
# 
# locale:
# [1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
# [3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
# [5] LC_TIME=Dutch_Netherlands.1252    
# 
# attached base packages:
# [1] stats     graphics  grDevices utils     datasets  methods   base     
# 
# other attached packages:
# [1] spatstat.geom_2.3-0 spatstat.data_2.1-0
# 
# loaded via a namespace (and not attached):
# [1] compiler_4.1.2       deldir_1.0-6         Matrix_1.3-4        
# [4] spatstat.utils_2.2-0 grid_4.1.2           polyclip_1.10-0     
# [7] lattice_0.20-45
```
